name: Build-Project
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
          # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Project
      uses: webbertakken/unity-builder@v1.5
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: .
        unityVersion: 2019.4.18f1
        targetPlatform: WebGL
    - name: Store Build
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: build
